# Generated by Django 6.0.3 on 2026-03-22 14:57

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('processing', 'Processing'), ('exported', 'Exported'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=15)),
                ('batch_code', models.CharField(blank=True, db_index=True, help_text='Auto-generated unique batch identifier.', max_length=50, unique=True)),
                ('batch_type', models.CharField(choices=[('farmer', 'Farmer Batch'), ('warehouse', 'Warehouse Batch'), ('product', 'Product Batch')], db_index=True, default='farmer', max_length=12)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('collection_location', models.CharField(blank=True, help_text='GPS or named location where produce was collected.', max_length=255)),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impurity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='farmers.farm')),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='farmers.farmer')),
                ('parent_batch', models.ForeignKey(blank=True, help_text='For warehouse/product batches aggregated from farmer batches.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='traceability.batch')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='farmers.product')),
            ],
            options={
                'verbose_name': 'Batch',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraceRecord',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('in_transit', 'In Transit'), ('at_warehouse', 'At Warehouse'), ('processing', 'Processing'), ('exported', 'Exported'), ('delivered', 'Delivered'), ('recalled', 'Recalled'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=15)),
                ('trace_code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('farmer_batch_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('warehouse_batch_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('product_batch_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('export_destination_country', models.CharField(blank=True, db_index=True, max_length=100)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('qr_code_image', models.ImageField(blank=True, help_text='Generated QR code image for physical labelling.', null=True, upload_to='trace/qr/%Y/%m/')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to='farmers.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_records', to='farmers.farmer')),
                ('field_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trace_records', to='farmers.product')),
            ],
            options={
                'verbose_name': 'Trace Record',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cert_type', models.CharField(choices=[('organic', 'Organic'), ('fairtrade', 'FairTrade'), ('rainforest', 'Rainforest Alliance'), ('global_gap', 'GlobalG.A.P.'), ('iso_22000', 'ISO 22000'), ('fssc_22000', 'FSSC 22000'), ('utz', 'UTZ Certified'), ('other', 'Other')], db_index=True, max_length=20)),
                ('cert_number', models.CharField(blank=True, max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=200)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=10)),
                ('document', models.FileField(blank=True, help_text='Uploaded certificate file (PDF).', null=True, upload_to='certifications/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('trace_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='traceability.tracerecord')),
            ],
            options={
                'verbose_name': 'Certification',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WarehouseIntake',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('code', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('altitude_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('polygon_coordinates', models.JSONField(blank=True, help_text='GeoJSON polygon [[lon,lat], ...] — closed ring required', null=True)),
                ('gps_accuracy_meters', models.FloatField(blank=True, help_text='GPS accuracy at capture time (metres)', null=True)),
                ('gps_captured_at', models.DateTimeField(blank=True, help_text='Timestamp when GPS coordinates were recorded in the field', null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_qc', 'Under QC'), ('passed', 'Passed QC'), ('rejected', 'Rejected'), ('processed', 'Processed')], db_index=True, default='received', max_length=15)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('warehouse_name', models.CharField(blank=True, max_length=200)),
                ('warehouse_location', models.CharField(blank=True, max_length=255)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross weight at intake.', max_digits=10)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Net weight after deducting impurities/moisture.', max_digits=10, null=True)),
                ('moisture_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impurity_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade_assigned', models.CharField(blank=True, max_length=20)),
                ('qc_report', models.TextField(blank=True, help_text='Full QC narrative report from the warehouse manager.')),
                ('rejection_reason', models.TextField(blank=True)),
                ('processing_notes', models.TextField(blank=True)),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_intake', to='traceability.batch')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_intakes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Intake',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tracerecord',
            name='warehouse_intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_records', to='traceability.warehouseintake'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['batch_type', 'status'], name='traceabilit_batch_t_5fb61c_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['farmer', 'batch_type'], name='traceabilit_farmer__527c36_idx'),
        ),
        migrations.AddIndex(
            model_name='tracerecord',
            index=models.Index(fields=['trace_code'], name='traceabilit_trace_c_bac70c_idx'),
        ),
        migrations.AddIndex(
            model_name='tracerecord',
            index=models.Index(fields=['farmer_batch_code'], name='traceabilit_farmer__54236e_idx'),
        ),
        migrations.AddIndex(
            model_name='tracerecord',
            index=models.Index(fields=['product_batch_code'], name='traceabilit_product_2ceb62_idx'),
        ),
        migrations.AddIndex(
            model_name='tracerecord',
            index=models.Index(fields=['status', 'export_destination_country'], name='traceabilit_status_fec30d_idx'),
        ),
    ]
