# Generated by Django 6.0.3 on 2026-03-22 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffApplication',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('ghana_card_number', models.CharField(db_index=True, help_text='Ghana National ID card number (GHA-XXXXXXXXX-X).', max_length=30, unique=True)),
                ('intended_role', models.CharField(choices=[('agronomist', 'Agronomist'), ('field_officer', 'Field Officer')], max_length=25)),
                ('educational_level', models.CharField(choices=[('none', 'No Formal Education'), ('primary', 'Primary'), ('jhs', 'Junior High School'), ('shs', 'Senior High School'), ('vocational', 'Vocational / Technical'), ('tertiary', 'Tertiary')], max_length=30)),
                ('preferred_region', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_staff_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('staff_id', models.CharField(db_index=True, max_length=30, unique=True)),
                ('role', models.CharField(choices=[('agronomist', 'Agronomist'), ('field_officer', 'Field Officer'), ('supervisor', 'Supervisor')], max_length=25)),
                ('ghana_card_number', models.CharField(max_length=30, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='pending', max_length=20)),
                ('source_application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resulting_profile', to='staff.staffapplication')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
