# Generated by Django 6.0.3 on 2026-03-22 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLockout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('locked_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(default='Too many failed login attempts', max_length=255)),
                ('locked_by', models.CharField(default='system', max_length=50)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Lockout',
            },
        ),
        migrations.CreateModel(
            name='BlacklistedEmailKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlacklistedPasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('resend_count', models.PositiveIntegerField(default=0)),
                ('resend_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('reset_count', models.PositiveIntegerField(default=0)),
                ('reset_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('phone', models.CharField(blank=True, help_text='E.164 format e.g. +233241234567. Unique per user. Enables phone-based login.', max_length=20, null=True, unique=True, verbose_name='phone number')),
                ('role', models.CharField(blank=True, choices=[('sa', 'Super Admin'), ('fo', 'Field Officer'), ('wm', 'Warehouse Manager'), ('by', 'Buyer'), ('fm', 'Farmer')], db_index=True, help_text="Platform role. Null or 'by' = sel-registered buyer. 'fo' = field officer. 'wm' = warehouse manager. 'fm' = farmer (registered by field officer). 'sa' = super admin.", max_length=2, null=True)),
                ('region', models.CharField(blank=True, help_text='Operational region (e.g. Brong-Ahafo, Upper West).', max_length=100, null=True, verbose_name='region')),
                ('district', models.CharField(blank=True, help_text='Operational district within the region.', max_length=100, null=True, verbose_name='district')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AdminImpersonationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('token_key', models.CharField(help_text='First 16 chars of impersonation token — for log correlation only.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='impersonation_actions', to=settings.AUTH_USER_MODEL)),
                ('impersonated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impersonation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Impersonation Log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPAuthenticator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], max_length=5)),
                ('phone', models.CharField(blank=True, help_text='E.164 format e.g. +233241234567. Required when channel=sms.', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_authenticator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Authenticator',
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=5)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'OTP Code',
                'indexes': [models.Index(fields=['user', 'channel'], name='accounts_ot_user_id_14f3b4_idx')],
            },
        ),
    ]
