# Generated by Django 6.0.3 on 2026-03-22 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_type', models.CharField(choices=[('farmer_summary', 'Farmer Summary'), ('farm_production', 'Farm Production'), ('staff_performance', 'Staff Performance'), ('traceability_chain', 'Traceability Chain'), ('warehouse_utilisation', 'Warehouse Utilisation'), ('order_summary', 'Order Summary'), ('payment_summary', 'Payment Summary'), ('buyer_activity', 'Buyer Activity'), ('impact_dashboard', 'Impact Dashboard'), ('co2_savings', 'CO2 Savings'), ('women_participation', 'Women Participation'), ('product_quality', 'Product Quality')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('output_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON'), ('xlsx', 'Excel')], default='csv', max_length=10)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('generating', 'Generating'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='queued', max_length=15)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Applied filters: region, district, date_from, date_to, year, month, officer_id, product_id, status.')),
                ('file', models.FileField(blank=True, help_text='Generated report file (CSV, PDF, XLSX, JSON).', null=True, upload_to='reports/%Y/%m/')),
                ('row_count', models.PositiveIntegerField(blank=True, help_text='Number of data rows in the generated report.', null=True)),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='User who triggered the report. Null for scheduled/system reports.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-queued_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['report_type', 'status'], name='reports_rep_report__4cebb9_idx'), models.Index(fields=['requested_by', 'queued_at'], name='reports_rep_request_53d033_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('report_type', models.CharField(choices=[('farmer_summary', 'Farmer Summary'), ('farm_production', 'Farm Production'), ('staff_performance', 'Staff Performance'), ('traceability_chain', 'Traceability Chain'), ('warehouse_utilisation', 'Warehouse Utilisation'), ('order_summary', 'Order Summary'), ('payment_summary', 'Payment Summary'), ('buyer_activity', 'Buyer Activity'), ('impact_dashboard', 'Impact Dashboard'), ('co2_savings', 'CO2 Savings'), ('women_participation', 'Women Participation'), ('product_quality', 'Product Quality')], db_index=True, max_length=40)),
                ('title', models.CharField(max_length=300)),
                ('output_format', models.CharField(choices=[('csv', 'CSV'), ('pdf', 'PDF'), ('json', 'JSON'), ('xlsx', 'Excel')], default='csv', max_length=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('recipients', models.JSONField(blank=True, default=list, help_text='Email addresses to receive the report when generated.')),
                ('is_enabled', models.BooleanField(db_index=True, default=True)),
                ('next_run_at', models.DateTimeField(blank=True, db_index=True, help_text='When the schedule will next generate a report.', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Schedule',
                'verbose_name_plural': 'Report Schedules',
                'ordering': ['next_run_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['is_enabled', 'next_run_at'], name='reports_rep_is_enab_ee3f40_idx')],
            },
        ),
    ]
