# Generated by Django 6.0.3 on 2026-03-22 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_farmers', models.PositiveIntegerField(default=0)),
                ('verified_farmers', models.PositiveIntegerField(default=0)),
                ('female_farmers', models.PositiveIntegerField(default=0)),
                ('farmers_this_month', models.PositiveIntegerField(default=0)),
                ('total_farms', models.PositiveIntegerField(default=0)),
                ('total_area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('avg_farm_area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('total_trace_records', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('exported_shipments', models.PositiveIntegerField(default=0)),
                ('destination_countries', models.PositiveIntegerField(default=0)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('orders_this_month', models.PositiveIntegerField(default=0)),
                ('total_revenue_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('revenue_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('total_buyers', models.PositiveIntegerField(default=0)),
                ('avg_order_value_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('active_field_officers', models.PositiveIntegerField(default=0)),
                ('total_farm_visits', models.PositiveIntegerField(default=0)),
                ('total_produce_kg', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('verification_rate_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('women_empowerment_pct', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Platform Snapshot',
            },
        ),
        migrations.CreateModel(
            name='RegionalSummary',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('region', models.CharField(db_index=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('farmer_count', models.PositiveIntegerField(default=0)),
                ('verified_count', models.PositiveIntegerField(default=0)),
                ('female_count', models.PositiveIntegerField(default=0)),
                ('new_farmers_mtd', models.PositiveIntegerField(default=0, help_text='Farmers registered in this specific month.')),
                ('farm_count', models.PositiveIntegerField(default=0)),
                ('total_area_ha', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batch_count', models.PositiveIntegerField(default=0)),
                ('total_weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('trace_records', models.PositiveIntegerField(default=0)),
                ('exported_count', models.PositiveIntegerField(default=0)),
                ('order_count', models.PositiveIntegerField(default=0)),
                ('revenue_ghs', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('officer_count', models.PositiveIntegerField(default=0)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('produce_kg', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Regional Summary',
                'ordering': ['-year', '-month', 'region'],
                'abstract': False,
                'indexes': [models.Index(fields=['region', 'year', 'month'], name='analytics_r_region_abf337_idx'), models.Index(fields=['year', 'month'], name='analytics_r_year_5fd2e3_idx')],
                'unique_together': {('region', 'year', 'month')},
            },
        ),
    ]
